"""Create initial tables

Revision ID: e5e287103206
Revises: 
Create Date: 2025-07-07 13:35:06.997824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e287103206'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_benchmarks_audience'), 'model_benchmarks', ['audience'], unique=False)
    op.create_index(op.f('ix_model_benchmarks_complexity'), 'model_benchmarks', ['complexity'], unique=False)
    op.create_index(op.f('ix_model_benchmarks_domain'), 'model_benchmarks', ['domain'], unique=False)
    op.create_index(op.f('ix_model_benchmarks_id'), 'model_benchmarks', ['id'], unique=False)
    op.create_index(op.f('ix_model_benchmarks_model_name'), 'model_benchmarks', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_benchmarks_task_type'), 'model_benchmarks', ['task_type'], unique=False)
    op.create_index(op.f('ix_model_benchmarks_tone'), 'model_benchmarks', ['tone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('prompt_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('predictions', sa.JSON(), nullable=True),
    sa.Column('refinements', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_analyses_id'), 'prompt_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_analyses_id'), table_name='prompt_analyses')
    op.drop_table('prompt_analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_benchmarks_tone'), table_name='model_benchmarks')
    op.drop_index(op.f('ix_model_benchmarks_task_type'), table_name='model_benchmarks')
    op.drop_index(op.f('ix_model_benchmarks_model_name'), table_name='model_benchmarks')
    op.drop_index(op.f('ix_model_benchmarks_id'), table_name='model_benchmarks')
    op.drop_index(op.f('ix_model_benchmarks_domain'), table_name='model_benchmarks')
    op.drop_index(op.f('ix_model_benchmarks_complexity'), table_name='model_benchmarks')
    op.drop_index(op.f('ix_model_benchmarks_audience'), table_name='model_benchmarks')
    op.drop_table('model_benchmarks')
    # ### end Alembic commands ###
